# Site settings
title: 진실리즘 (Jinsilism)
tagline : 퇴사 후 세계여행을 꿈꾸는 진실의 여행기
description: "The Adventure of Jinsil."
url: "http://jinsilism.com"
author:
  name: "Jinsilism"
  email: "jinsilism@gmail.com"
  url: "http://jinsilism.com"

# Build settings
baseurl: /
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: Jinsilism
