# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'ujinsil'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID:

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'World Trip', folder: 'pages', file: 'worldtrip.html'}
- {name: 'Sool-Safari', folder: 'pages', file: 'Sool-safari.html'}
- {name: 'Europe', folder: 'pages', file: 'europe.html'}
- {name: 'South America', folder: 'pages', file: 'south-america.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCObsVlGykSzqmkRj_ufjSfw'}
- {icon: 'facebook', link: 'https://www.facebook.com/jinsilism'}
- {icon: 'instagram', link: 'https://instagram.com/jimsil_travel'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jinsilyu/'}
- {icon: 'envelope', link: 'mailto:jinsilism@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
